lidar_preprocess: # 点云数据预处理(以下参数均定义在车辆坐标系下，正x轴指向车前，正y轴指向车左，正z轴指向车顶，符合右手定则，单位均为m，参数调节请使用可视化点云)
  near_roi: # 近端自车反射产生的噪点范围，范围之内的点云直接滤除，x轴[-1.25,2.30],y轴[-0.40,0.40]
    near_noise_x_min: 0.50
    near_noise_x_max: 2.50
    near_noise_y_min: -0.70
    near_noise_y_max: 0.70
  trailer_noise: # 由于后方拖挂车反射产生的噪点范围，范围之内的点云直接滤除，其中trailer_x_max = near_noise_x_min，x轴[-1.70,-1.25]，y轴[-1.30,1.30]
    trailer_x_min: -2.50
    trailer_y_min: -2.00
    trailer_y_max: 2.00
  far_roi: # 水平方向ROI范围，范围之外的点云直接滤除，x轴[-10.00,30.00]，y轴[-10.00,10.00]
    livox_roi_x_min: -10.00
    livox_roi_x_max: 30.00
    livox_roi_y_min: -10.00
    livox_roi_y_max: 10.00
  z_roi: # 高度方向ROI范围，范围之外的点云直接滤除，z轴[-0.50,1.40]
    livox_roi_z_min: -0.25
    livox_roi_z_max: 1.50
  near_noise_filter: # 由于大疆雷达自身的缺陷，在近端会产生异常噪点，下面做滤波处理
    livox_noise_flag: true 
    roi: # 定义近端处理范围，范围內的点云会被处理，x轴[-5.00,10.00]，y轴[-6.00,6.00]
      livox_noise_x_min: -5.00
      livox_noise_x_max: 10.00
      livox_noise_y_min: -6.00
      livox_noise_y_max: 6.00
    rate: # 调节阈值，阈值过大会滤除正常点，阈值过小会残留噪点，调节范围[0.0010, 0.0020]
      livox_noise_rate: 0.0020
    min_direct_remove_intensity: 0.7
  outlier_remove: # 离群点去除
    min_outlier_intensity: 25.00 # 强度阈值，离群点一般强度低于此值
    search_radius: 0.80 # 每个点的考察半径，如果考察半径內少于min_neighbors个点，就当做离群点，调节范围[0.80, 2.00]
    min_neighbors: 7 # 考察半径內最少的近邻点个数，为整数，调节范围[3, 7]
  frame_merging: # 大疆雷达50ms一帧，这里叠加多帧点云进行处理，此参数不宜过大，满足要求即可，调节范围[4, 8]
    frame_merging_count: 5 # 注意是整数

ground_segmentation: # 点云预处理中一个子步骤，地面点云滤除
  n_bins: 25 # 径向栅格个数，为整数，调节范围[20,35]
  n_segments: 50 # 角度段数，为整数，调节范围[40, 70]
  gamma_rate: 0.70 # 径向栅格划分形变因子，值越小，近处栅格越密集，远处栅格越稀疏，调节范围[0.4, 1.0]
  prior_ground_z: 0.00 # 车辆坐标系原点的z坐标
  max_initial_slope: 0.04 # 初始斜率阈值，值越大越能处理坡度大的地面，但不能过大，容易出现过分割地面，满足要求即可，调节范围[0.03, 0.06]
  max_slope: 0.02 # 斜率阈值，含义同上，调节范围[0.01,0.03]
  line_search_segment_num: 3 # 角度段方向搜索邻域范围，不宜过大，满足要求即可，调节范围[1,5]
  max_dist_to_line: 0.30 # 判断是否为地面阈值，不宜过大，满足要求即可，调节范围[0.20,0.35]

grid_map: # 栅格图中相关参数
  roi_map: # ROI区域栅格图，这里同lidar_preprocess/far_roi中的设置
    min_x: -10.00
    max_x: 30.00
    min_y: -10.00
    max_y: 10.00
    pixel_scale: 10 # 栅格图分辨率，1m有10个栅格

reference_line:
  frame_merging_count: 10 # 叠加帧数，此帧数相比于静态栅格图可适量多些
  ref_x_min: -10.00
  ref_x_max: 30.00
  ref_y_min: 0.00 # 只考虑左侧墙壁
  ref_y_max: 20.00
  ref_z_min: 3.00 # 高度阈值，既要滤除掉低矮车辆，又要保留墙壁点云
  ref_z_max: 3.50
  wall_distance: 9.5 # 左侧墙壁到中心线的距离
