Min_ref_speed: 12.5
K_ref_0_20: 0.8
K_ref_20_40: 0.5
K_ref_40_60: 0.2
Kp_error: 0.2
Ki_error: 0.05
filter_param: 0.3
Kp_wheel: 9250.0
uturn_wheel_max: 4800
Straight_preview_dis: 10.0
TurnRight_preview_dis: 5.0
TurnLeft_preview_dis: 5.0
Uturn_preview_dis: 3.5
Parking_preview_dis: 3.5
Launch_preview_dis: 7.0
RRT_preview_dis: 3.5

speed_kp: 200.0
speed_ki: 3.0
speed_kd: 0.0
speed_kv: 25.0
speed_ka: 400.0
speed_max: 30.0
speed_min: 5.0
emergency_slow_brake: 15
emergency_stop_brake: 30
eps_distance: 1.0
eps_angle: 0.523598
filter_cmd: 0.25
filter_brake_cmd: 0.25

speed_error_list: [-1, -2, -3, -4, -6, -8]
brake_cmd_list: [1, 2, 4, 8, 10, 20]

min_vehicle_speed_kmph_for_acc_constrain: 3 # 自车速度到达多少km/h之后才开始限制加速，避免无法起步
